analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning 

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
